### PR TITLE
Introduce maintanance staff contact for medical manager

### PR DESCRIPTION
**Pull request by ashutoshc8101**
https://user-images.githubusercontent.com/24855641/189946086-e58fd16a-c64b-4c08-916a-79d37ea02bfe.mp4

### CODE REVIEW

**Review by iraapp — APPROVED** [review]

**Comment by iraapp** [comment]
@Jeetu303 Please review the video.

**Comment by Jeetu303** [comment]
Refer UI. after logging in, your interface and the UI do not match. Maintenance shows some red-colored text. Remove unwanted text and page.
@ashutoshc8101 get back after doing indeed things

**Comment by ashutoshc8101** [comment]
> Refer UI. after logging in, your interface and the UI do not match. Maintenance shows some red-colored text. Remove unwanted text and page. @ashutoshc8101 get back after doing indeed things

image

**Comment by Jeetu303** [comment]
All good Go ahead and merge pr @ashutoshc8101

**Pull request merged**
