### PR TITLE
Integrate doctor appointments and history

### PR DESCRIPTION
**Pull request by ashutoshc8101**
Integrete doctor appointments and history

https://user-images.githubusercontent.com/24855641/188983968-cb985a41-cf1d-477d-bcd9-23a256b89a33.mp4

### CODE REVIEW

**Comment by ashutoshc8101** [comment]
@Jeetu303 Please approve the video.

**Review by iraapp — APPROVED** [review]

**Comment by Jeetu303** [comment]
While an appointment is requested and is in process. it should not show the time. Remove the time slot field from appointments (in the process).
When a requested appointment is rejected, it should show only rejected not the timing. Only Approved appointments should show timing... Neither rejected nor in process, the appointment should show timing. 
All other things are fine @ashutoshc8101

**Comment by ashutoshc8101** [comment]
@Jeetu303 Please re-review

**Comment by Jeetu303** [comment]
Great All good
Go ahead

**Pull request merged**
